- hosts:
  - bastions
  - servers
  - workers
  roles:
    - common

- hosts:
  - bastions
  roles:
    - bastion

- hosts:
  - servers
  - workers
  roles:
    - cluster

- hosts:
  - servers
  roles:
    - server
