bastions:
	hosts:
		jumpbox:
			ansible_host: 10.152.159.153

workers:
	hosts:
		node0:
			ansible_host: 10.152.159.225
		node1:
			ansible_host: 10.152.159.162

controllers:
	hosts:
		server:
			ansible_host: 10.152.159.115

